# Generated by Django 4.2.1 on 2023-05-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('result_1', models.IntegerField()),
                ('result_2', models.IntegerField()),
                ('result_3', models.IntegerField()),
                ('result_4', models.IntegerField()),
            ],
        ),
    ]
